# Generated by Django 3.2.5 on 2021-07-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloned', '0003_auto_20210714_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nick_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
