# Generated by Django 3.2.5 on 2021-07-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloned', '0004_auto_20210712_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
